### ISSUE TITLE
No overload matches this call in utils file

### ISSUE THREAD

**Issue by ThimoDEV** [mezg0/vue-ui#1]
![image](https://github.com/mezg0/vue-ui/assets/68739517/7267f484-4c4a-422f-8b74-e7ad06b97120)

It shows on line 17 in the utils file `return h(slots.default()[0], { ...attrs })`

Steps to reproduce: 

- install the required dependencies
- Create a utils folder in nuxt
- Create a utils.ts file
- Import the utils code
- See the error happening

**Comment by mezg0** [comment]
Which version of nuxt are you using?

**Comment by ThimoDEV** [comment]
> Which version of nuxt are you using?

I use Nuxt 3.6.2

**Comment by mezg0** [comment]
Any chance you can reproduce it on a codesandbox? 

I made one quickly and can't see the error -> https://codesandbox.io/p/sandbox/wandering-cache-wzpphn?file=%2Flib%2Futils.ts%3A8%2C1

**Comment by ThimoDEV** [comment]
I'll do as soon as I can

**Comment by ThimoDEV** [comment]
I tried to make another reproduction, but I couldn't get the same error. The code does work and a temp workaround can be used with a ttypescript ignore
