### ISSUE TITLE
Disable scroll when Dialog, Sheet, etc is open.

### ISSUE THREAD

**Issue by Blinks44** [mezg0/vue-ui#2]
First of all, i appreciate your work man, keep going, vue world deserve frontend libraries like shadcnui!

I noticed one problem with all dialogs that has overlay, all of them should disable scroll behavior when opened. Originaly ```ark-ui``` adds classes to ```html``` and ```body``` tags to prevent this, but not in your library. I tried to understand why, but with no luck...

![2023-07-10_11-45-54](https://github.com/mezg0/vue-ui/assets/8570193/e524318e-1edf-4cd0-983d-c163118e6e1c)

**Comment by mezg0** [comment]
Looks to be a bug with the Vue version of ark https://github.com/chakra-ui/ark/issues/1167.

For now you can use the `@open` and `@close` events to handle it manually. I might add it as a workaround in the docs for now

**Comment by mezg0** [comment]
Looks like ark has the functionality behind a [prop](https://ark-ui.com/docs/vue/components/dialog/props#:~:text=dialog%20is%20open-,preventScroll,-boolean).

I've updated the component -> https://ui.mezg0.com/component/alert-dialog

**Comment by Blinks44** [comment]
Ahh, their docs lying that prevent scroll is the default behaviour… I think Sheet component should have preventscroll prop too?
