### ISSUE TITLE
Fresh install doesn't work.

### ISSUE THREAD

**Issue by Blinks44** [mezg0/vue-ui#3]
Fresh install ```Vite + Vue + TS``` (not ```Nuxt```, vanilla ```Vue``` app) shows typescript errors and doesn't work. Tailwind and all dependencies are installed. What am i doing wrong?) Or for now it is just works with nuxt?

Reproduction - https://codesandbox.io/p/sandbox/vigorous-kilby-y9z767

**Comment by mezg0** [comment]
Looks like you need the vueJSX vite plugin to make jsx work with vite -> https://www.npmjs.com/package/@vitejs/plugin-vue-jsx

Working sandbox: https://codesandbox.io/p/sandbox/trusting-andras-2vrckg

I'll add a note to the docs. Thanks for the heads up

**Comment by Blinks44** [comment]
Thanks!
